# Generated by Django 6.1.1 on 2026-10-06 09:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffresApp', '0001_initial'),
        ('VehiculesApp', '0002_remove_vehicule_offre_alter_vehicule_capacite_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='vehicule',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='VehiculesApp.vehicule'),
            preserve_default=False,
        ),
    ]
