# Generated by Django 6.1.1 on 2026-09-29 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntreprisesApp', '0001_initial'),
        ('OffresApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=11, unique=True)),
                ('type_vehicule', models.CharField(choices=[('cam', 'camionnette'), ('four', 'fourgon'), ('camp', 'camion porteur'), ('semi', 'semi-remorque')], default='cam', max_length=20)),
                ('capacite_kg', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='OffresApp.offre')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='EntreprisesApp.entreprise')),
            ],
        ),
    ]
