# Generated by Django 6.1.1 on 2026-10-06 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehiculesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='offre',
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='capacite_kg',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100, "La capacité doit être d'au moins 100 kg")]),
        ),
    ]
