# Generated by Django 6.1.1 on 2026-10-06 09:53

import EntreprisesApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntreprisesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, 'Adresse doit contenir au moins 10 caractères'), django.core.validators.MaxLengthValidator(200, 'Adresse ne doit pas dépasser 200 caractères')]),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='matricule_fiscale',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='format incorrect -ex(1234567AAM000 ou 1234567-A-A-M-000).', regex='^\\d{7}[/ -]?[A-Za-z][/ -]?[ABDNPEabdnpe][/ -]?[MPCNEmpcne][/ -]?\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[EntreprisesApp.models.validate_email]),
        ),
    ]
